### ISSUE TITLE
Error in bind_user method

### ISSUE THREAD

**Issue by fengyc** [admiralobvious/flask-simpleldap#25]
Hi. There may be a bug in bind_user method. 

The code `self.get_object_details(user=username, dn_only=True)` returns a string in python3,  so `user_dn` should be a string and doesn't have `decode` method.

My test environment : python3.5  openldap  flask-simpleldap-1.1.0  pyldap-2.4.25.1

**Comment by FREImedia** [comment]
I got exactly the same problem!
python3.5

**Comment by catsem** [comment]
Same here on Python 3.4.3
From Traceback:
    `conn.simple_bind_s(user_dn.decode('utf-8'), password)`
    `AttributeError: 'str' object has no attribute 'decode'`

**Comment by theneedyguy** [comment]
Same here...

    File "/usr/local/lib/python3.5/dist-packages/flask_simpleldap/__init__.py", line 152, in bind_user

    conn.simple_bind_s(user_dn.decode('utf-8'), password)

    AttributeError: 'str' object has no attribute 'decode'

I can only get it to work with python2.7 instead of python 3.5.

**Comment by admiralobvious** [comment]
Fixed in version 1.1.2.
